[ Refactor ] reformat, fix typo, remove unused
Hod0ri/2022-CoSW_Server pull request #2
Opened 2022-11-02 02:37 UTC by qsef1256

2022-11-02 03:14 UTC, Hod0ri requested changes

2022-11-02 03:14 UTC, Hod0ri commented on swServer/src/main/java/com/daelim/swserver/auth/controller/UserController.java
> +    @Autowired
의존성 주입시, 아래와 같이 사용하여도 스프링에서 구동시 Bean으로 자동으로 등록됨
```java
@Autowired
private UserRepository userRepository
```

2022-11-02 03:14 UTC, Hod0ri commented on swServer/src/main/java/com/daelim/swserver/auth/controller/UserController.java
> +        log.info("Request : " + userdto);
사용자 로그 부분은 테스팅용으로 둔 로그이기에 삭제할 예정

2022-11-02 03:37 UTC, qsef1256 commented on swServer/src/main/java/com/daelim/swserver/auth/controller/UserController.java
> +    @Autowired
잘 알고 있지만, field injection 은 Unit Test 시 문제가 있는 등 여러가지 이유로 권장되지 않으므로 setter based 로 바꿨습니다.

2022-11-02 03:40 UTC, qsef1256 commented on swServer/src/main/java/com/daelim/swserver/auth/controller/UserController.java
> +    @Autowired
https://yaboong.github.io/spring/2019/08/29/why-field-injection-is-bad/

2022-11-02 15:14 UTC, Hod0ri commented on swServer/src/main/java/com/daelim/swserver/auth/controller/UserController.java
> +    @Autowired
컨테이너 환경이라 아직 Unit Test 등 여건을 고려하지 않았기에 필드 주입을 사용했습니다.
정 그러면, 생성자 주입 방식으로 통일하는건 어떨까요?

2022-11-03 14:18 UTC, Hod0ri reviewed
생성자 주입으로 통일 의견

2022-11-03 15:30 UTC, qsef1256 commented on swServer/src/main/java/com/daelim/swserver/auth/controller/UserController.java
> +    @Autowired
생성자 주입으로 변경하였습니다.

2022-11-09 16:23 UTC, merged